class BeaconModel {
  final String id,
      beacon_name,
      merchant_id,
      store_id,
      beacon_id,
      major,
      minor,
      tx_power,
      beacon_country,
      beacon_state,
      beacon_city,
      beacon_address,
      beacon_latitude,
      beacon_longitude,
      description,
      password,
      beacon_type,
      added_by,
      added_on,
      update_on,
      status;

  BeaconModel._(
      {required this.id,
      required this.beacon_name,
      required this.merchant_id,
      required this.store_id,
      required this.beacon_id,
      required this.major,
      required this.minor,
      required this.tx_power,
      required this.beacon_country,
      required this.beacon_state,
      required this.beacon_city,
      required this.beacon_address,
      required this.beacon_latitude,
      required this.beacon_longitude,
      required this.description,
      required this.password,
      required this.beacon_type,
      required this.added_by,
      required this.added_on,
      required this.update_on,
      required this.status});

  factory BeaconModel.fromJson(Map<String, dynamic> json) {
    return new BeaconModel._(
        id: json['id'],
        beacon_name: json['beacon_name'],
        merchant_id: json['merchant_id'],
        store_id: json['store_id'],
        beacon_id: json['beacon_id'],
        major: json['major'],
        minor: json['minor'],
        tx_power: json['tx_power'],
        beacon_country: json['beacon_country'],
        beacon_state: json['beacon_state'],
        beacon_city: json['beacon_city'],
        beacon_address: json['beacon_address'],
        beacon_latitude: json['beacon_latitude'],
        beacon_longitude: json['beacon_longitude'],
        description: json['description'],
        password: json['password'],
        beacon_type: json['beacon_type'],
        added_by: json['added_by'],
        added_on: json['added_on'],
        update_on: json['update_on'],
        status: json['status']);
  }
}
