class OrderListModel {
  var id,
      booking_id,
      user_id,
      store_id,
      merchant_id,
      purchase_type,
      address_id,
      address_type,
      group_id,
      sub_total,
      delivery_amount,
      discounted_amount,
      merchant_phone,
      merchant_country_code,
      total_amount,
      total_payed_amount,
      tax,
      extra_charge,
      tx_id,
      status,
      payment_status,
      added_on,
      update_on,
      currency,
      currency_sign,
      payment_mode,
      store_name,
      store_logo,
      user_name,
      country_code,
      user_phone,
      user_email,
      store_logo_thumb;


  OrderListModel._({
    this.id,
    this.booking_id,
    this.user_id,
    this.store_id,
    this.merchant_id,
    this.purchase_type,
    this.address_id,
    this.address_type,
    this.group_id,
    this.sub_total,
    this.delivery_amount,
    this.discounted_amount,
    this.merchant_phone,
    this.merchant_country_code,
    this.total_amount,
    this.total_payed_amount,
    this.tax,
    this.extra_charge,
    this.tx_id,
    this.status,
    this.payment_status,
    this.added_on,
    this.update_on,
    this.currency,
    this.currency_sign,
    this.payment_mode,
    this.store_name,
    this.store_logo,
    this.user_name,
    this.country_code,
    this.user_phone,
    this.user_email,
    this.store_logo_thumb
  });

  factory OrderListModel.fromJson(Map<String, dynamic> json) {
    return new OrderListModel._(
        id: json['id'],
        booking_id: json['booking_id'],
        user_id: json['user_id'],
        store_id: json['store_id'],
        merchant_id: json['merchant_id'],
        purchase_type: json['purchase_type'],
        address_id: json['address_id'],
        address_type: json['address_type'],
        group_id: json['group_id'],
        sub_total: json['sub_total'],
        delivery_amount: json['delivery_amount'],
        discounted_amount: json['discounted_amount'],
        merchant_phone: json['merchant_phone'],
        merchant_country_code: json['merchant_country_code'],
        total_amount: json['total_amount'],
        total_payed_amount: json['total_payed_amount'],
        tax: json['tax'],
        extra_charge: json['extra_charge'],
        tx_id: json['tx_id'],
        status: json['status'],
        payment_status: json['payment_status'],
        added_on: json['added_on'],
        update_on: json['update_on'],
        currency: json['currency'],
        currency_sign: json['currency_sign'],
        payment_mode: json['payment_mode'],
        store_name: json['store_name'],
        store_logo: json['store_logo'],
        user_name: json['user_name'],
        country_code: json['country_code'],
        user_phone: json['user_phone'],
        user_email: json['user_email'],
        store_logo_thumb: json['store_logo_thumb']
    );
  }
}
