class ProductCartModel {
//  id: 17,
//  merchant_id: 71,
//  store_id: 18,
//  name: 43,
//  category: 0,
//  price: rqwd,
//  offers: asd,
//  discount: dsafdsafds,
//  description: vdsfd,
//  imgs: ["653a3a72-5fb1-4195-9558-a01f0751edf17829549901043010010.jpg"],
//  status: 1
  var id,
      merchant_id,
      cart_id,
      store_id,
      name,
      category,
      price,
      offers,
      discount,
      description,
      imgs,
      status,
      qty,
      offers_detail,
      discount_price,
      currency,
      product_id,
      offfer_price,
      applyed_offer;
  ProductCartModel._({
    this.id,
    this.merchant_id,
    this.cart_id,
    this.store_id,
    this.name,
    this.category,
    this.price,
    this.offers,
    this.discount,
    this.description,
    this.imgs,
    this.status,
    this.qty,
    this.offers_detail,
    this.discount_price,
    this.currency,
    this.product_id,
    this.offfer_price,
    this.applyed_offer,
  });

  factory ProductCartModel.fromJson(Map<String, dynamic> json) {
    return new ProductCartModel._(
      id: json['id'],
      merchant_id: json['merchant_id'],
      cart_id: json['cart_id'],
      store_id: json['store_id'],
      name: json['name'],
      category: json['category'],
      price: json['price'],
      offers: json['offers'],
      discount: json['discount'],
      description: json['description'],
      imgs: json['imgs'],
      status: json['status'],
      qty: json['qty'],
      offers_detail: json['offers_detail'],
      discount_price: json['discount_price'],
      currency: json['currency'],
      product_id: json['product_id'],
      offfer_price: json['offfer_price'],
      applyed_offer: json['applyed_offer'],
    );
  }
}
