class StoreModel {
  var id,
      merchant_id,
      store_name,
      store_logo,
      store_country,
      store_state,
      store_city,
      store_address,
      store_latitude,
      store_longitude,
      status,
      open_time,
      close_time,
      is_favourite,
      total_weight,
      rating;
/*"id": "23",
                "merchant_id": "18",
                "store_name": "Brand factory ",
                "store_logo": "https://alphaxtech.net/ecity/uploads/stores/download.jpg",
                "store_country": "India",
                "store_state": "MP",
                "store_city": "Indore",
                "store_address": "LIG INDORE",
                "store_latitude": "22.7321115",
                "store_longitude": "22.7322225",
                "store_description": "We have very uniq collections",
                "open_time": "14:00",
                "close_time": "18:00",
                "rating": "0",
                "is_favourite": "1",
                "total_weight": "4.3",
                "store_logo_thumb": "https://alphaxtech.net/ecity/uploads/stores/thumb/download.jpg"*/
  StoreModel._(
      {this.id,
      this.merchant_id,
      this.store_name,
      this.store_logo,
      this.store_country,
      this.store_state,
      this.store_city,
      this.store_address,
      this.store_latitude,
      this.store_longitude,
      this.status,
      this.open_time,
      this.close_time,
      this.is_favourite,
      this.total_weight,
      this.rating
      });

  factory StoreModel.fromJson(Map<String, dynamic> json) {
    return new StoreModel._(
      id: json['id'],
      merchant_id: json['merchant_id'],
      store_name: json['store_name'],
      store_logo: json['store_logo'],
      store_country: json['store_country'],
      store_state: json['store_state'],
      store_city: json['store_city'],
      store_address: json['store_address'],
      store_latitude: json['store_latitude'],
      store_longitude: json['store_longitude'],
      status: json['status'],
      open_time: json['open_time'],
      close_time: json['close_time'],
      is_favourite: json['is_favourite'],
      total_weight: json['total_weight'],
      rating: json['rating'],
    );
  }
}
